baseURL = "https://simracingdublin.ie"
title = "Sim Racing Dublin"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "spectral"

[params]
fancyTitle = "Sim Racing Dublin"
description = 'A new experience coming soon!'
body_is_markdown = true
#images = ["path_to_social_image_for_link_previews.jpg"]

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'