baseURL = "https://simracingdublin.ie"
title = "Sim Racing Dublin | Ireland"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "spectral"

[params]
fancyTitle = "Sim Racing Dublin"
description = 'A new experience coming soon!'
body_is_markdown = true
#images = ["path_to_social_image_for_link_previews.jpg"]

# language specific options

[languages.en]
weight = 0
languageName = "English"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[[module.mounts]]
source = 'scripts'
target = 'static/scripts'